version: 0.2

phases:
  install:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 507542660958.dkr.ecr.us-west-2.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t shimabu:latest .
      - docker tag shimabu:latest 507542660958.dkr.ecr.us-west-2.amazonaws.com/shimabu:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 507542660958.dkr.ecr.us-west-2.amazonaws.com/shimabu:latest
      - echo Deploying the Docker image to ECS...
      - |
        ecs deploy ${ECS_SERVICE} \
        --image 507542660958.dkr.ecr.us-west-2.amazonaws.com/shimabu:latest \
        --timeout 600 \
        --cluster ${ECS_CLUSTER} \
        --region us-west-2
