import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Links from '../../components/Links'
import {Headline} from '../../components/Headline'
import Main from '../../components/main'

function tadanoalert(){
    alert('tadanoalert')
}


export default function Home() {
    return (
        <>
            <Head>
                <title>Index Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Main />
        </>
    )
}
